### ISSUE TITLE
server/server.go - panic close of closed channel

### ISSUE THREAD

**Issue by oysterpack** [capnproto/go-capnproto2#101]
When running tests, I occasionally observe a panic on line 130 in [server/server.go](https://github.com/capnproto/go-capnproto2/blob/master/server/server.go). I put in a quick fix to work around the issue. The quick fix is to simply ignore the panic triggered by closing the closed channel. 

    func (s *server) Close() error {
	    // There is some concurrency issue because sometimes the channel is already closed, and closing a closed channel
	    // triggers a panic. For now, simply wrap the channel close step and ignore any panic
	    func() {
		defer func() {
			recover()
		}()
		close(s.stop) 
	    }()
	    <-s.done
	    if s.closer == nil {
		return nil
	    }
	    return s.closer.Close()
    }

**Comment by zombiezen** [comment]
`Close()` should not be called more than once... I suspect that this is happening in your code because of the observations noted in #69.  Without further evidence, I don't think it will be feasible to fix this before v3.

**Comment by oysterpack** [comment]
Thanks for the explanation. What is the timeline for v3 ? What's planned for v3 ? Is there a roadmap available ?

btw, capnp + rpc rocks, and I see tremendous potential ...

**Comment by zombiezen** [comment]
You can follow the [3.0 milestone](https://github.com/capnproto/go-capnproto2/milestone/1) to see the list of items I consider in scope for v3.  There's no exact timeline, since it's in a "as I get time" basis (or as there are more contributors :smiley:), but I am actively working on it in the [v3 branch](https://github.com/capnproto/go-capnproto2/compare/v3).  The primary focus is on fixing the architectural flaws with the rpc package that make bugs like the one you're seeing possible.
