### ISSUE TITLE
Registering several listeners for same rpc.NewConn

### ISSUE THREAD

**Issue by thedanielforum** [capnproto/go-capnproto2#130]
I am trying to listen for calls for two diffrent protos using the same `rpc.NewConn` connection, however I can't figure out how to do it.
I've tried with the following code.
```go
// Create a new locally implemented accountFactory.
accountSrv := account.AccountFactory_ServerToClient(accountMethods.AccountFactory{})
// Create a new locally implemented transferFactory.
transferSrv := transfer.TransferFactory_ServerToClient(transferMethods.TransferFactory{})

// Listen for calls, using the accountFactory as the bootstrap interface.
conn := rpc.NewConn(
	rpc.StreamTransport(c),
	rpc.MainInterface(transferSrv.Client),
	rpc.MainInterface(accountSrv.Client),
)
defer conn.Wait()
```
The calls to `accountSrv.Client` will go through, but all calls for `transferSrv.Client` will result in the following error.
```
protos/transfer/transfer.capnp:TransferFactory.transferFunds: rpc exception: @0xc93b78b26d6cd25a.@0: capnp: method not implemented
```

All help would be greatly appreciated!

**Comment by zenhack** [comment]
Capnproto rpc doesn't support more than one bootstrap interface. If you want to construct a bootstrap object that dispatches to one or other, you can use the `*_Methods` generated functions on both servers and combine them with server.New. See also #86.

Note that this has slightly different behavior than exporting two independent objects, since the methods for both get handled by the same goroutine, so they'll be serialized.

An alternative would be to make the bootstrap interface an object with methods that are getters for the other two objects.

**Comment by zombiezen** [comment]
Closing this out, since it sounds like this has been resolved.

(Thanks @zenhack!)
