### ISSUE TITLE
Recursive RPC call hangs indefinitely

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#138]
I'm writing a recursive procedure in which a method handler must be able to issue the same RPC call back to the caller in order to return a response.

I've boiled down this scenario to the following (very synthetic) test case.  The basic idea is that vat 1 calls the `Foo` method on vat 2, which then calls the `Foo` method on vat 1.  Vat 2 then returns the result from its RPC call as the result to the original RPC call.

**Problem:** The code below hangs indefinitely.  Note that changing `p.SetDepth(1)` to `p.SetDepth(0)` behaves as expected (because the second, i.e. recursive, RPC call is never issued against the caller).

What gives?  Is this behavior fundamentally incompatible with (go-)capnproto?

```capnproto
using Go = import "/go.capnp";
$Go.import("lthibault/capnp-scratchpad");

@0x923d0572ed1463e4;
$Go.package("api");

interface Fooer {
    foo @0 (depth :Int) -> (id :Int);
}
```

```go
package api

import (
	"context"
	"log"
	"net"
	"testing"

	"github.com/stretchr/testify/assert"
	"zombiezen.com/go/capnproto2/rpc"
)

type foo struct {
	id   int8
	next *Fooer
}

func (f foo) Foo(call Fooer_foo) error {
	log.Printf("in %d, depth=%d\n", f.id, call.Params.Depth())

	if call.Params.Depth() == 0 {
		call.Results.SetId(f.id)
		return nil
	}

	p := f.next.Foo(call.Ctx, func(param Fooer_foo_Params) error {
		param.SetDepth(call.Params.Depth() - 1)
		return nil
	})

	res, err := p.Struct()
	if err != nil {
		return err
	}

	call.Results.SetId(res.Id())
	return nil
}

func TestFooer(t *testing.T) {
	p0, p1 := net.Pipe()

	foo0 := &foo{id: 0}
	foo1 := &foo{id: 1}

	main := Fooer_ServerToClient(foo0)
	conn := rpc.NewConn(rpc.StreamTransport(p0), rpc.MainInterface(main.Client))
	f0 := &Fooer{Client: conn.Bootstrap(context.Background())}

	main = Fooer_ServerToClient(foo1)
	conn = rpc.NewConn(rpc.StreamTransport(p1), rpc.MainInterface(main.Client))
	f1 := &Fooer{Client: conn.Bootstrap(context.Background())}

	foo0.next = f1
	foo1.next = f0

	res, err := f0.Foo(context.Background(), func(p Fooer_foo_Params) error {
		p.SetDepth(1) // this works when set to 0
		return nil
	}).Struct()
	if err != nil {
		log.Fatal(err)
	}

	if !assert.Equal(t, int8(1), res.Id()) {
		t.FailNow()
	}
}
```

**Comment by zombiezen** [comment]
Hello again! Unfortunately, with the way that the v2 API and internals are structured, it's pretty easy to get into scenarios like this with moderately complex object access patterns. The main reason is that the v2 RPC internals generally hold locks while entering user code, especially before the method acks the call. I have a v3 branch rewrite of the RPC system that attempts to ameliorate this. However, such a scenario that involves self-calls can always occur since Cap'n Proto only gives backpressure ability at the transport layer.

Unfortunately, the v3 development been stalled since I haven't had the energy to complete it. I can't really give any sort of estimate on when this would be done, but all the low-level code is mostly working, it's just a matter of finishing the last 5-10% of the spec to get back to level 1/2.

**Comment by lthibault** [comment]
Hello again! :)
IIUC, you're saying this kind of issue is a fundamental consequence of Capnp's design (not just your library)? 

If so, it's not a problem. I went with capnp primarily for the data serialization, which works quite nicely. 

Thanks for the quick feedback, as usual!

**Comment by zombiezen** [comment]
The backpressure issue: yes. The Go implementation just exacerbates it due to some flaws in how I implemented it.

**Comment by zenhack** [comment]
I think on v3 this should always work provided you call `.Ack()` before issuing the recursive call.

Is there anything actionable here, or can we close?

**Comment by lthibault** [comment]
Yeah this can definitely be closed.  I was using v2 at the time.
