### ISSUE TITLE
Any way to recovery from panics

### ISSUE THREAD

**Issue by b00f** [capnproto/go-capnproto2#156]
Panic in RPC calls, will crash the whole application, which is not good (It should be zero cost calling a RPC method, right?).
We can have a recovery plan on top of each methods (interface) that looks to be redundant. The better way is to recover from the panics internally. 
Is there any strategy for recovering from the panic inside capnp?

**Comment by zombiezen** [comment]
Catching panics is generally considered an anti-pattern because after a panic there's no guarantee the process is still in a consistent state. golang/go#16542 documents that `net/http`'s behavior is for backwards compatibility purposes. grpc/grpc-go#441 documents the reasons why they do not catch panics. This package will not catch panics for the same reasons.
